### PR TITLE
Check for image match in updatePcieFpga

### PR DESCRIPTION
**Pull request by bhill-slac**
Puts matching images at top of list and prompts for
confirmation if image name does not match.
Guards against accidentally loading wrong image.

Note that many of the diff changes are due to adding a test for a valid
entry selected which required an indent in the next code block.

### CODE REVIEW

**Comment by ruck314** [comment]
@bhill-slac I got this error message when I ran your script:
```bash
$ python scripts/updatePcieFpga.py --path ../firmware/targets/SnlLenetKcu1500/images/
  File "scripts/updatePcieFpga.py", line 20
    print(f"Basedir = {baseDir}")
                               ^
SyntaxError: invalid syntax
```

**Comment by ruck314** [comment]
@bhill-slac If I select the `exit` option, it hangs and never exits:
```bash
$ python scripts/updatePcieFpga.py --path ../firmware/targets/SnlLenetKcu1500/images/
Rogue/pyrogue version v5.9.3. https://github.com/slaclab/rogue
Basedir = /afs/slac.stanford.edu/u/re/ruckman/projects/snl-lenet-dev/firmware/submodules/axi-pcie-core/scripts
Start: Started zmqServer on ports 9099-9101
WARNING: PcieTop.AxiPcieCore.numDmaLanes = 1 != PcieTop.AxiPcieCore.AxiVersion.DMA_SIZE_G = 4
#########################################
Current Firmware Loaded on the PCIe card:
#########################################
Path         = PcieTop.AxiPcieCore.AxiVersion
FwVersion    = 0x7060000
UpTime       = 1 day, 21:38:06
GitHash      = 0x99a8a856a5e043dd12ff8511d79441e6c5d48cf
XilinxDnaId  = 0x40020001012967a904402345
FwTarget     = ClinkSlacPgpCardG4Pgp4
BuildEnv     = Vivado v2021.1
BuildServer  = rdsrv302 (Ubuntu 20.04.2 LTS)
BuildDate    = Thu 26 Aug 2021 10:42:18 AM PDT
Builder      = ruckman
#########################################
0 : ../firmware/targets/SnlLenetKcu1500/images/SnlLenetKcu1500-0x01000000-20210910101242-ruckman-d20d716
1 : Exit
Enter image to program into the PCIe card's PROM: 1
```

**Comment by ruck314** [comment]
@bhill-slac I tried upgrading a ClinkSlacPgpCardG4Pgp4@v7.6.0 to ClinkSlacPgpCardG4Pgp4@v7.7.0.  It has that the image name does not match the current image on the PCIe card.  This seems wrong because it is the same image name but just a newer FW tag release.
```bash
$ python scripts/updatePcieFpga.py --path ~/projects/cameralink-gateway/firmware/targets/ClinkKcu1500Pgp4/images/
Rogue/pyrogue version v5.9.3. https://github.com/slaclab/rogue
Basedir = /afs/slac.stanford.edu/u/re/ruckman/projects/snl-lenet-dev/firmware/submodules/axi-pcie-core/scripts
Start: Started zmqServer on ports 9099-9101
WARNING: PcieTop.AxiPcieCore.numDmaLanes = 1 != PcieTop.AxiPcieCore.AxiVersion.DMA_SIZE_G = 4
#########################################
Current Firmware Loaded on the PCIe card:
#########################################
Path         = PcieTop.AxiPcieCore.AxiVersion
FwVersion    = 0x7060000
UpTime       = 1 day, 21:48:53
GitHash      = 0x99a8a856a5e043dd12ff8511d79441e6c5d48cf
XilinxDnaId  = 0x40020001012967a904402345
FwTarget     = ClinkSlacPgpCardG4Pgp4
BuildEnv     = Vivado v2021.1
BuildServer  = rdsrv302 (Ubuntu 20.04.2 LTS)
BuildDate    = Thu 26 Aug 2021 10:42:18 AM PDT
Builder      = ruckman
#########################################
0 : /u/re/ruckman/projects/cameralink-gateway/firmware/targets/ClinkKcu1500Pgp4/images/ClinkKcu1500Pgp4-0x07070000-20210908142757-ruckman-0c5ccad
1 : Exit
Enter image to program into the PCIe card's PROM: 0
Selected image does not match current image ClinkSlacPgpCardG4Pgp4.
Are you sure? (y/n):
```

**Comment by bhill-slac** [comment]
I've been seeing the problem with python not exiting for some time now whenever I update my firmware.    Same with this version.   It hangs if I update the firmware and hangs if I select the new exit option.     I guess I should have filed a jira issue.

**Comment by bhill-slac** [comment]
Re the imageMatch, in your example the AxiVersion shows 
FwTarget     = ClinkSlacPgpCardG4Pgp4
but the selected image filename was
ClinkKcu1500Pgp4-0x07070000-20210908142757-ruckman-0c5ccad

This is exactly the issue I wanted to confirm, as twice now I've accidentally loaded kcu1500 firmware onto a PGP4 card or vice versa.   Whenever that happens I need to pull the card so it can be reprogrammed via jtag.

I'm open to other ways to help guard against this.    Could we get a different PCIE device ID so we can tell the cards apart?

**Pull request merged**
